{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "mqtt-sensor-exporter.fullname" . }}-manager-role
  labels:
    {{- include "mqtt-sensor-exporter.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - iot.hauke.cloud
  resources:
  - databases
  - devices
  - mqttbridges
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.hauke.cloud
  resources:
  - databases/status
  - devices/status
  - mqttbridges/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - create
  - get
  - list
  - update
  - patch
{{- with .Values.rbac.rules }}
{{ toYaml . }}
{{- end }}
{{- end }}
